### ISSUE TITLE
Source for .xz archives

### ISSUE THREAD

**Issue by jackson5sec** [iComputer7/ancient-ubuntu-docker#1]
Not an issue but where were you pulling the archives for these images from? Or was this taken directly out of each iso

https://github.com/iComputer7/ancient-ubuntu-docker/blob/master/gutsy/ubuntu-7.10-root.tar.xz

**Comment by iComputer7** [comment]
It's been so long, I don't remember. I think I just went on google and searched for OpenVZ container images.
